package scaffold

import (
	"fmt"
	"path/filepath"
	"strings"
)

// ctrlFilesFromPairs 生成 api 聚合接口与多文件 Controller。
// 完全由 v1 DTO 配对驱动，不写死任何方法。
func ctrlFilesFromPairs(name string, modulePath string, pairs []v1Pair) map[string]string {
	pkg := sanitizeIdentifier(name)
	title := pascal(pkg)
	files := map[string]string{
		filepath.Join("api", pkg, pkg+".go"):                        apiInterfaceFile(modulePath, pkg, title, pairs),
		filepath.Join("internal", "controller", pkg, pkg+".go"):     fmt.Sprintf("// Code generated by gap once. Add module-specific controller helpers here.\n\npackage %s\n", pkg),
		filepath.Join("internal", "controller", pkg, pkg+"_new.go"): ctrlNewFile(modulePath, pkg),
	}
	for _, p := range pairs {
		files[filepath.Join("internal", "controller", pkg, methodFile(pkg+"_v1_", p.Method))] = ctrlMethodFile(modulePath, pkg, title, p)
	}
	return files
}

func apiInterfaceFile(modulePath string, pkg string, title string, pairs []v1Pair) string {
	var b strings.Builder
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import (\n\t\"context\"\n\n\tv1 \"" + modulePath + "/api/" + pkg + "/v1\"\n)\n\n")
	b.WriteString("type I" + title + "V1 interface {\n")
	for _, p := range pairs {
		b.WriteString("\t" + p.Method + "(ctx context.Context, req *v1." + p.ReqName + ") (res *v1." + p.ResName + ", err error)\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func ctrlNewFile(modulePath string, pkg string) string {
	title := pascal(pkg)
	return fmt.Sprintf(`package %s

import "%s/api/%s"

type ControllerV1 struct{}

func NewV1() %s.I%sV1 {
	return &ControllerV1{}
}
`, pkg, modulePath, pkg, pkg, title)
}

// ctrlMethodFile 生成单方法 Controller 占位。
// 业务逻辑尚未实现，先返回 nil, nil 由用户后续补齐。
func ctrlMethodFile(modulePath string, pkg string, title string, p v1Pair) string {
	var b strings.Builder
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import (\n\t\"context\"\n\n")
	b.WriteString("\tv1 \"" + modulePath + "/api/" + pkg + "/v1\"\n)\n\n")
	b.WriteString("func (c *ControllerV1) " + p.Method + "(ctx context.Context, req *v1." + p.ReqName + ") (*v1." + p.ResName + ", error) {\n")
	b.WriteString("\t// TODO: 实现 " + p.Method + " 业务逻辑\n")
	b.WriteString("\treturn nil, nil\n}\n")
	return b.String()
}
